<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>WinFocus</RootNamespace>
    <ApplicationIcon>Assets/WindowIcon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;arm64</Platforms>
    <RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
    <PublishProfile>Properties\PublishProfiles\win10-$(Platform).pubxml</PublishProfile>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <GenerateAppInstallerFile>False</GenerateAppInstallerFile>
    <AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
    <PackageCertificateThumbprint>667C15B09F5993F52470A485E8449AC92581B0CC</PackageCertificateThumbprint>
    <AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
    <AppxAutoIncrementPackageRevision>False</AppxAutoIncrementPackageRevision>
    <AppxSymbolPackageEnabled>True</AppxSymbolPackageEnabled>
    <GenerateTestArtifacts>True</GenerateTestArtifacts>
    <AppxBundle>Always</AppxBundle>
    <AppxBundlePlatforms>x64</AppxBundlePlatforms>
    <AppInstallerUri>https://cloudrive.albresky.cn/public/WinFocus/WinFocus_v2.0.0.0.msix</AppInstallerUri>
    <Configurations>Debug;Release;All</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <Content Remove="Assets\add.png" />
    <Content Remove="Assets\Video\Video.mp4" />
    <Content Remove="Assets\WindowIcon.ico" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Controls\DialogInfo.xaml" />
    <None Remove="Views\BingWallpaperPage.xaml" />
    <None Remove="Views\LiveWallpaperGalleryPage.xaml" />
    <None Remove="Views\LiveWallpaperPage.xaml" />
    <None Remove="Views\MediaPlayerPage.xaml" />
    <None Remove="Views\VideoGridViewPage.xaml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\WinFocus.Core\WinFocus.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.0.0" />
    <PackageReference Include="CommunityToolkit.WinUI.UI.Animations" Version="7.1.2" />
    <PackageReference Include="CommunityToolkit.WinUI.UI.Controls" Version="7.1.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="7.0.0" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.2.221209.1" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.WinUI.Managed" Version="2.0.9" />
    <PackageReference Include="WinUIEx" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Assets\focus_page.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\LargeTile.scale-100.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\LargeTile.scale-125.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\LargeTile.scale-150.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\LargeTile.scale-200.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\LargeTile.scale-400.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\SmallTile.scale-100.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\SmallTile.scale-125.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\SmallTile.scale-150.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\SmallTile.scale-200.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\SmallTile.scale-400.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\Square150x150Logo.scale-100.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\Square150x150Logo.scale-125.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\Square150x150Logo.scale-150.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\Square150x150Logo.scale-200.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\Square150x150Logo.scale-400.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\Wide310x150Logo.scale-100.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\Wide310x150Logo.scale-125.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\Wide310x150Logo.scale-150.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\Wide310x150Logo.scale-200.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\Wide310x150Logo.scale-400.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\WindowIcon.altform-lightunplated_targetsize-16.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\WindowIcon.altform-lightunplated_targetsize-24.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\WindowIcon.altform-lightunplated_targetsize-256.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\WindowIcon.altform-lightunplated_targetsize-32.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\WindowIcon.altform-lightunplated_targetsize-48.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\WindowIcon.altform-unplated_targetsize-16.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\WindowIcon.altform-unplated_targetsize-24.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\WindowIcon.altform-unplated_targetsize-256.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\WindowIcon.altform-unplated_targetsize-32.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\WindowIcon.altform-unplated_targetsize-48.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\WindowIcon.scale-100.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\WindowIcon.scale-125.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\WindowIcon.scale-150.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\WindowIcon.scale-200.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\WindowIcon.scale-400.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\WindowIcon.targetsize-16.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\WindowIcon.targetsize-24.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\WindowIcon.targetsize-256.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\WindowIcon.targetsize-32.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Assets\WindowIcon.targetsize-48.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Assets\add.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Video\Video.mp4">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Assets\WindowIcon.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <Page Update="Views\BingWallpaperPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\VideoGridViewPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\MediaPlayerPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\LiveWallpaperGalleryPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\LiveWallpaperPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Controls\DialogInfo.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>
  
  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>
</Project>
